openapi: 3.0.0
info:
  title: 12-Social-Network
  version: 1.0.0
servers:
  - url: https://social-network-api-us5x.onrender.com/api/v1
tags:
  - name: Auth
  - name: Users
  - name: Followers
  - name: Posts
  - name: Comments
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: ilija
                username: ilijas19
                email: ilijagocic1971@gmail.com
                password: secret
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: ilijagocic1971@gmail.com
                password: secret
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /auth/verify-email:
    post:
      tags:
        - Auth
      summary: Verify Email
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                verificationToken: >-
                  c053439ece28ff054d5acb29160d21f83d7da62554ad28b9dfdce035972e07a9c12755d32b5607a8
                email: ilijagocic1971@gmail.com
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /auth/forgot-password:
    post:
      tags:
        - Auth
      summary: Forgot Password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: ilijagocic1971@gmail.com
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /auth/reset-password:
    post:
      tags:
        - Auth
      summary: Reset Password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: ilijagocic1971@gmail.com
                token: >-
                  763ee9ebf8f9bcc4982194c333117a9da40377ddd1bdab1bc35026d66d49ac47c8bb06f60ca944c5
                password: ilijas19
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /auth/logout:
    get:
      tags:
        - Auth
      summary: Logout User
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users:
    get:
      tags:
        - Users
      summary: Get All Users
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/search:
    get:
      tags:
        - Users
      summary: Search For Users
      parameters:
        - name: name
          in: query
          schema:
            type: string
          example: ilija
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/{id}:
    get:
      tags:
        - Users
      summary: Get Single User
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/showMe:
    get:
      tags:
        - Users
      summary: Show Current User
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/updateUser:
    patch:
      tags:
        - Users
      summary: Update User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Ilija Gocic
                bio: 21 Year Old Backend Developer
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/updateUserPassword:
    patch:
      tags:
        - Users
      summary: Update User Password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                currentPassword: secret
                newPassword: secret
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/uploadProfilePicture:
    post:
      tags:
        - Users
      summary: Upload Profile Picture
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /users/deleteUser:
    delete:
      tags:
        - Users
      summary: Delete User
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /followers/follow/{id}:
    get:
      tags:
        - Followers
      summary: Follow User
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user to follow
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /followers/unfollow/{id}:
    get:
      tags:
        - Followers
      summary: Unfollow User
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user to unfollow
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /followers/getFollowing:
    get:
      tags:
        - Followers
      summary: Get Following List
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /followers/getFollowers:
    get:
      tags:
        - Followers
      summary: Get Followers List
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /posts:
    post:
      tags:
        - Posts
      summary: Upload Post
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                caption:
                  type: string
                  example: lorem lorem
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Posts
      summary: Get All My Posts
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /posts/{id}:
    get:
      tags:
        - Posts
      summary: Get Single Post
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the post
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - Posts
      summary: Update Post
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the post to update
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                caption: updated lorem lorr
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Posts
      summary: Delete Post
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the post to delete
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /posts/save/{id}:
    get:
      tags:
        - Posts
      summary: Save Post
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the post to save
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /posts/unsave/{id}:
    get:
      tags:
        - Posts
      summary: Unsave Post
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the post to unsave
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /comments/{id}:
    get:
      tags:
        - Comments
      summary: Get Comments of a Post
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the post to get comments from
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Comments
      summary: Add Comment to Post
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the post to comment on
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                text: wow
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /comments/update/{id}:
    patch:
      tags:
        - Comments
      summary: Update Comment
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the comment to update
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                text: updated wow
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Comments
      summary: Delete Comment
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the comment to delete
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
